### ISSUE TITLE
Usage guide

### ISSUE THREAD

**Issue by filipenevola** [Procempa/meteor-keycloak-auth#1]
Hi, I'll need to create something similar to use keycloak.

Can you create a simple usage guide in README.md?

Thank you.

**Comment by delki8** [comment]
+1

**Comment by danilo-favoratti** [comment]
+1

**Comment by omeuerodrigofreitas** [comment]
+1

**Comment by fredmaiaarantes** [comment]
+1

**Comment by edimarlnx** [comment]
+1

**Comment by filipeportes** [comment]
+1

**Comment by oliveirasWell** [comment]
+1

**Comment by silveirado** [comment]
Filipe, apreciamos sua contribuição para o projeto. Breve estaremos publicando uma guia básico de utilização.

**Comment by betovieirasilva** [comment]
+1

**Comment by thiagoneves1** [comment]
+1

**Comment by pvmilreu** [comment]
+1

**Comment by silveirado** [comment]
Basis usage sample add to README.md.

**Comment by filipenevola** [comment]
hi @silveirado , I guess it is missing the configuration part, no?

Probably we need to setup endpoints and auth credentials.

**Comment by silveirado** [comment]
yeap, you need to create keycloak.json in assets folder with your realm configuration.
