### ISSUE TITLE
WRONG URL REDIRECT

### ISSUE THREAD

**Issue by jamalazza** [Procempa/meteor-keycloak-auth#2]
I'm trying to integrate keycloak with meteor but there is a problem with the url:

instead of url part saying 'tokens/login?' it must be 'protocol/openid-connect/auth?'

Can you fix these please??

**Comment by silveirado** [comment]
Work in progress... we will release a new version shortly. tx.

**Comment by silveirado** [comment]
Solved in version 0.9.1
