### ISSUE TITLE
Error in login response 

### ISSUE THREAD

**Issue by jamalazza** [Procempa/meteor-keycloak-auth#3]
I get this error while authenticating the client
Error in login response: unauthorized_client - Invalid client secret.
Error in OAuth Server: Cannot read property 'serviceData' of undefined

the client secret is correct I verified it several times.
Any advise please

![screenshot from 2016-07-08 00-49-54](https://cloud.githubusercontent.com/assets/16616664/16674318/60c07488-44a6-11e6-9122-43bf7f4b0c63.png)

**Comment by jamalazza** [comment]
Finally I found the problem.
in keycloack_server.js I found this :

`headers = {
            'Content-Length': params.length,
            'Content-Type': 'application/x-www-form-urlencoded',
            'Authorization': 'Basic ' + new Buffer(config.resource + ':' + configFile['realm-public-key']).toString('base64'),
        };`

but instead it should be:

`headers = {
            'Content-Length': params.length,
            'Content-Type': 'application/x-www-form-urlencoded',
            'Authorization': 'Basic ' + new Buffer(config.resource + ':' + configFile['credentials'].secret).toString('base64'),
        };`

**just replace configFile['realm-public-key'] by configFile['credentials'].secret**
Can you please update the package??
Thanks

**Comment by jamalazza** [comment]
Sorry Closed by error

**Comment by silveirado** [comment]
Hi, the current code is working for public access type client setting on keycloak. I have fixed to accept both access types. Tx for your collaboration!
